[package]
name = "nutorch"
version = "0.0.1"
edition = "2021"
license = "MIT"
authors = ["Ryan X. Charles <ryan@ryanxcharles.com>"]

[dependencies]
tch = { version = "0.20.0", features = ["download-libtorch"] }
